#.travis.yml

language: node_js
sudo: false
dist: trusty
node_js:
  - 13

branches:
  except:
    - gh-pages

cache:
  directories:
    - node_modules

script:
  - npm run prod

notifications:
  email:
    on_failure: change
    on_success: change

before_deploy:
  - cp dist/index.html dist/404.html

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
